"use client";
import { FormEvent, useState } from "react";
export default function PasswordResetPanel({ role }: { role: "student" | "enterprise" }) {
  const [step, setStep] = useState(1), [challengeId, setChallengeId] = useState(""), [proof, setProof] = useState(""), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  async function post(path: string, payload: Record<string, string>) { const response = await fetch(path, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json() as Record<string, string>; if (!response.ok) throw new Error(result.error || "操作未完成"); return result; }
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const data = new FormData(event.currentTarget); try { if (step === 1) { const result = await post("/api/auth/password/forgot", { email: String(data.get("email") || "") }); setChallengeId(result.challengeId || ""); setStep(2); } else if (step === 2) { const result = await post("/api/auth/password/verify", { challengeId, code: String(data.get("code") || "") }); setProof(result.proof); setStep(3); } else { const password = String(data.get("password") || ""), confirmation = String(data.get("confirmation") || ""); if (password !== confirmation) throw new Error("两次输入的密码不一致"); await post("/api/auth/password/reset", { challengeId, proof, password }); setStep(4); } } catch (reason) { setError(reason instanceof Error ? reason.message : "操作未完成"); } finally { setBusy(false); } }
  if (step === 4) return <div className="auth-card auth-reset-success"><span>✓</span><h2>密码已重置</h2><p>所有旧登录会话已安全退出，请使用新密码重新登录。</p><a className="auth-submit" href={`/auth/${role}`}>返回登录</a></div>;
  return <div className="auth-card"><header><small>PASSWORD RECOVERY</small><h2>找回密码</h2><p>第 {step} 步，共 3 步</p></header><div className="reset-progress"><i className="on"/><i className={step >= 2 ? "on" : ""}/><i className={step >= 3 ? "on" : ""}/></div><form onSubmit={submit}>{step === 1 && <label><span>注册邮箱</span><input name="email" type="email" autoComplete="email" placeholder="name@example.com" required/></label>}{step === 2 && <label><span>6 位验证码</span><input name="code" inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" maxLength={6} placeholder="000000" required/></label>}{step === 3 && <><label><span>新密码</span><input name="password" type="password" autoComplete="new-password" pattern="[!-~]{8,20}" minLength={8} maxLength={20} placeholder="8-20 位英文、数字与符号" required/></label><label><span>确认新密码</span><input name="confirmation" type="password" autoComplete="new-password" minLength={8} maxLength={20} required/></label></>}{error && <p className="auth-error" role="alert">{error}</p>}<button className="auth-submit" disabled={busy}>{busy ? "正在处理…" : step === 1 ? "发送验证码" : step === 2 ? "验证并继续" : "重置密码"}</button><a className="auth-forgot" href={`/auth/${role}`}>返回登录</a></form></div>;
}
