import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, mkdir, writeFile, readFile, rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { DatabaseSync } from 'node:sqlite';
import { createFileStore } from '../server/files.mjs';
test('backup retains WAL-committed rows, private files and authentication config', async t => {
  const { backupData } = await import('../scripts/backup.mjs');
  const root = await mkdtemp(join(tmpdir(), 'starlight-backup-'));
  let db;
  t.after(async () => { db?.close(); await rm(root, { recursive: true, force: true }); });
  const data = join(root, 'data'); await mkdir(data);
  db = new DatabaseSync(join(data, 'app.sqlite'));
  db.exec("PRAGMA journal_mode=WAL;CREATE TABLE records(id INTEGER PRIMARY KEY, value TEXT);INSERT INTO records VALUES(1,'committed')");
  await createFileStore(join(data, 'files')).put('resume/a.pdf', Buffer.from('resume'), { customMetadata: { owner: 'student', visibility: 'private' } });
  const config = join(root, 'runtime.json'); await writeFile(config, JSON.stringify({ AUTH_PEPPER: 'retained-private-test-secret' }));
  await writeFile(join(data, 'restore-complete.json'), '{}');
  const target = join(root, 'backup'); await backupData(data, target, config);
  await assert.rejects(backupData(data, join(root, 'no-space'), config, { reserveBytes: Number.MAX_SAFE_INTEGER }), /space/i);
  const restored = new DatabaseSync(join(target, 'app.sqlite'));
  assert.equal(restored.prepare('SELECT value FROM records WHERE id=1').get().value, 'committed'); restored.close();
  const asset = await createFileStore(join(target, 'files')).get('resume/a.pdf');
  assert.equal(asset.customMetadata.visibility, 'private');
  assert.equal(await new Response(asset.body).text(), 'resume');
  assert.equal(JSON.parse(await readFile(join(target, 'runtime.json'), 'utf8')).AUTH_PEPPER, 'retained-private-test-secret');
  assert.equal(JSON.parse(await readFile(join(target, 'backup-complete.json'), 'utf8')).fileCount, 1);
  await assert.rejects(backupData(data, target, config), /exist/i);
});
