"use client";
import { useEffect, useState } from "react";
import { studentRequest } from "./useStudentData";

export default function StudentSharePanel({ flash }: { flash: (message: string) => void }) {
  const [days, setDays] = useState(30), [activeUntil, setActiveUntil] = useState(""), [url, setUrl] = useState(""), [busy, setBusy] = useState(false);
  useEffect(() => { studentRequest("/api/student/share").then((response) => response.json()).then((data) => setActiveUntil(data.share?.expiresAt || "")).catch(() => {}); }, []);
  const create = async () => { setBusy(true); try { const response = await studentRequest("/api/student/share", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ days }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "生成失败"); setUrl(data.url); setActiveUntil(data.expiresAt); await navigator.clipboard.writeText(data.url); flash("公开成长档案链接已生成并复制"); } catch (error) { flash(error instanceof Error ? error.message : "生成失败"); } finally { setBusy(false); } };
  const revoke = async () => { setBusy(true); try { const response = await studentRequest("/api/student/share", { method: "DELETE" }); if (!response.ok) throw new Error("停用失败"); setUrl(""); setActiveUntil(""); flash("公开成长档案链接已停用"); } catch (error) { flash(error instanceof Error ? error.message : "停用失败"); } finally { setBusy(false); } };
  return <section className="student-share-card"><header><span>↗</span><div><small>PUBLIC PROFILE</small><h3>公开成长档案</h3></div></header><p>生成无需登录即可查看的独立链接，只展示你设为公开的成长经历，不包含联系方式和简历文件。</p><label><span>链接有效期</span><select value={days} onChange={(event) => setDays(Number(event.target.value))}><option value={7}>7 天</option><option value={30}>30 天</option><option value={90}>90 天</option></select></label>{activeUntil ? <small className="share-active">当前有一条有效链接，有效期至 {new Date(activeUntil).toLocaleDateString("zh-CN")}</small> : null}{url ? <div className="share-url"><input readOnly value={url}/><button onClick={async () => { await navigator.clipboard.writeText(url); flash("链接已复制"); }}>复制</button></div> : null}<div><button className="primary-btn" disabled={busy} onClick={create}>{busy ? "正在处理…" : activeUntil ? "重新生成链接" : "生成并复制链接"}</button>{activeUntil ? <button className="danger-text-btn" disabled={busy} onClick={revoke}>停用链接</button> : null}</div></section>;
}
