/* eslint-disable @next/next/no-img-element */
"use client";
import {useEffect,useState} from "react";
import Link from "next/link";

type RecordItem={id:string;kind:string;payload:Record<string,unknown>;updatedAt:string};
type Log={id:number;actorId:string;action:string;targetType:string;targetId:string;createdAt:string};
type Registration={id:string;activityId:string;activityTitle:string;answers:Record<string,string>;status:string;createdAt:string};
type Field={id:string;label:string;type:string;required:boolean};
const reviewable=["job","activity","content"];
const kindName=(kind:string)=>kind==="job"?"岗位":kind==="activity"?"活动":kind==="content"?"成长内容":"企业资料";
const stateName=(state:unknown)=>state==="approved"?"已通过":state==="rejected"?"已退回":"待审核";
const fieldOptions:Field[]=[{id:"name",label:"姓名",type:"text",required:true},{id:"phone",label:"联系电话",type:"tel",required:true},{id:"email",label:"常用邮箱",type:"email",required:true},{id:"school",label:"学校、专业与年级",type:"text",required:true},{id:"studentId",label:"学号",type:"text",required:false},{id:"expectation",label:"参加活动的期待",type:"textarea",required:false}];

export default function JAConsole({operator}:{operator:string}){
 const [tab,setTab]=useState("review"),[records,setRecords]=useState<RecordItem[]>([]),[logs,setLogs]=useState<Log[]>([]),[registrations,setRegistrations]=useState<Registration[]>([]),[notice,setNotice]=useState(""),[selectedId,setSelectedId]=useState(""),[selectedRegistration,setSelectedRegistration]=useState<Registration|null>(null),[reason,setReason]=useState(""),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);const response=await fetch("/api/admin");const data=await response.json();setRecords(data.records||[]);setLogs(data.logs||[]);setRegistrations(data.registrations||[]);setLoading(false)};
 useEffect(()=>{let active=true;fetch("/api/admin").then(response=>response.json()).then(data=>{if(active){setRecords(data.records||[]);setLogs(data.logs||[]);setRegistrations(data.registrations||[]);setLoading(false)}});return()=>{active=false}},[]);
 const pending=records.filter(r=>reviewable.includes(r.kind)&&(!r.payload.reviewStatus||r.payload.reviewStatus==="pending"));
 const selected=records.find(r=>r.id===selectedId);
 const decide=async(decision:"approved"|"rejected")=>{if(!selected)return;if(decision==="rejected"&&!reason.trim()){setNotice("退回时请填写具体修改意见");return}const response=await fetch("/api/admin",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({id:selected.id,decision,reason:reason.trim()})});const data=await response.json();if(!response.ok){setNotice(data.error||"审核失败");return}setNotice(decision==="approved"?"审核通过：该内容现在会进入学生端公开目录":"已退回：企业端会显示修改意见");setSelectedId("");setReason("");await load()};
 const title=tab==="review"?"企业发布审核":tab==="publish"?"JA 内容发布":tab==="registrations"?"活动报名数据":tab==="records"?"平台内容":"审计日志";
 const description=tab==="review"?"审核企业提交的岗位、活动与成长内容，确认后再向学生端公开。":tab==="publish"?"由 JA 直接发布活动、文章或视频，并配置学生报名信息。":tab==="registrations"?"查看全部活动报名及学生填写的信息。":tab==="records"?"集中查看平台已经提交和发布的内容状态。":"记录后台的重要操作，便于追踪审核与发布过程。";
 return <main className="ja-console platform v2 ja-platform"><aside className="side"><Link href="/" className="side-brand official-side-brand"><img src="/media/ja-china-logo.jpg" alt="JA China"/><b>星光计划</b></Link><nav><button className={tab==="review"?"active":""} onClick={()=>setTab("review")}><span>✓</span>统一审核 <i>{pending.length}</i></button><button className={tab==="publish"?"active":""} onClick={()=>setTab("publish")}><span>＋</span>内容发布</button><button className={tab==="registrations"?"active":""} onClick={()=>setTab("registrations")}><span>☷</span>报名数据 <i>{registrations.length}</i></button><button className={tab==="records"?"active":""} onClick={()=>setTab("records")}><span>▱</span>平台内容</button><button className={tab==="audit"?"active":""} onClick={()=>setTab("audit")}><span>◷</span>审计日志</button></nav><div className="side-help"><b>后台操作提示</b><p>企业提交内容先由 JA 审核；审核通过后才会进入学生端公开目录。</p></div><a className="back" href="/signout-with-chatgpt?return_to=/">退出后台</a></aside><div className="work"><header className="topbar"><div className="workspace-context"><small>JA OPERATIONS</small><b>长沙运营后台</b><span>内容审核与平台运营</span></div><div className="top-actions"><span className="operator-name">{operator}</span><div className="avatar">JA</div></div></header><section className="workspace ja-workspace"><div className="page-title"><div><small>JA CHANGSHA OPERATIONS</small><h1>{title}</h1><p>{description}</p></div></div><div className="ja-view" key={tab}>
 {notice&&<p className="admin-notice">{notice}</p>}
 {tab==="review"&&<><section className="admin-test-guide"><div><small>如何测试审核闭环</small><h2>企业提交 → JA 审核 → 学生端公开</h2></div><ol><li><b>1</b><span>在<a href="/workspace?role=enterprise" target="_blank">企业端</a>新建内容并提交</span></li><li><b>2</b><span>回到此页刷新，打开详情并通过或退回</span></li><li><b>3</b><span>通过后到<a href="/workspace?role=student" target="_blank">学生端</a>查看</span></li></ol><button onClick={load}>刷新待审核列表</button></section><div className="admin-records">{loading?<div className="admin-empty">正在读取审核队列…</div>:pending.length===0?<div className="admin-empty">当前没有待审核内容，请先从企业端提交一条测试内容</div>:pending.map(r=><article key={r.id}><span>{kindName(r.kind)}</span><div><small>{String(r.payload.company||r.payload.category||"长沙企业")}{r.payload.jobCategory?` · ${String(r.payload.jobCategory)}`:""}</small><h2>{String(r.payload.title||"未命名内容")}</h2><p>{String(r.payload.summary||"无简介")}</p><em>提交于 {new Date(String(r.payload.submittedAt||r.updatedAt)).toLocaleString("zh-CN")}</em></div><button className="inspect" onClick={()=>{setSelectedId(r.id);setReason("")}}>查看并审核</button></article>)}</div></>}
 {tab==="publish"&&<AdminPublisher onPublished={async message=>{setNotice(message);await load()}}/>}
 {tab==="registrations"&&<RegistrationTable items={registrations} onSelect={setSelectedRegistration} onRefresh={load}/>} 
 {tab==="records"&&<div className="admin-records records-view">{records.filter(r=>reviewable.includes(r.kind)).map(r=><article key={r.id}><span>{kindName(r.kind)}</span><div><small>{String(r.payload.company||r.payload.category||"长沙平台内容")}</small><h2>{String(r.payload.title||"未命名")}</h2><p>{stateName(r.payload.reviewStatus)}{r.payload.reviewNote?` · ${String(r.payload.reviewNote)}`:""}</p></div><button className="inspect" onClick={()=>setSelectedId(r.id)}>查看详情</button></article>)}</div>}
 {tab==="audit"&&<div className="admin-table"><div><b>时间</b><b>动作</b><b>对象</b><b>操作者</b></div>{logs.map(l=><div key={l.id}><span>{new Date(l.createdAt).toLocaleString("zh-CN")}</span><span>{l.action}</span><span>{l.targetType} · {l.targetId}</span><span>{l.actorId.slice(0,18)}…</span></div>)}</div>}
 </div></section></div>{selected&&<ReviewDrawer selected={selected} reason={reason} setReason={setReason} decide={decide} close={()=>{setSelectedId("");setReason("")}}/>}{selectedRegistration&&<RegistrationDrawer item={selectedRegistration} onClose={()=>setSelectedRegistration(null)}/>}</main>
}

function AdminPublisher({onPublished}:{onPublished:(message:string)=>Promise<void>}){
 const [kind,setKind]=useState<"activity"|"content">("activity"),[saving,setSaving]=useState(false),[fields,setFields]=useState(["name","phone","school"]),[custom,setCustom]=useState(""),[form,setForm]=useState({title:"",summary:"",place:"长沙",date:"",capacity:"100",category:"JA 成长活动",duration:"10 分钟",mediaType:"article",cover:"/media/ja-career-fair.jpg",coverType:"image"});
 const change=(key:string,value:string)=>setForm(v=>({...v,[key]:value}));
 const media=async(file?:File)=>{if(!file)return;const data=new FormData();data.append("file",file);data.append("purpose","media");const response=await fetch("/api/files",{method:"POST",body:data});const result=await response.json();if(response.ok&&result.url)setForm(v=>({...v,cover:result.url,coverType:String(result.type).startsWith("video/")?"video":"image",mediaType:String(result.type).startsWith("video/")?"video":v.mediaType}))};
 const publish=async()=>{if(!form.title.trim()||!form.summary.trim())return;setSaving(true);const registrationFields=[...fieldOptions.filter(x=>fields.includes(x.id)),...custom.split("\n").map(x=>x.trim()).filter(Boolean).map((label,index)=>({id:`custom_${index+1}`,label,type:"textarea",required:false}))];const payload=kind==="activity"?{title:form.title,summary:form.summary,place:form.place.includes("长沙")?form.place:`长沙 · ${form.place}`,date:form.date||"待定",capacity:Number(form.capacity)||100,registered:0,category:form.category,cover:form.cover,coverType:form.coverType,registrationFields}:{title:form.title,summary:form.summary,category:form.category,duration:form.duration,level:"入门",mediaType:form.mediaType,cover:form.cover,coverType:form.coverType};const response=await fetch("/api/admin",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({kind,payload})});const result=await response.json();setSaving(false);if(!response.ok){await onPublished(result.error||"发布失败");return}setForm(v=>({...v,title:"",summary:""}));await onPublished("JA 内容已直接发布，学生端刷新后即可看到")};
 return <section className="admin-publisher"><div className="admin-publisher-intro"><small>DIRECT PUBLISH</small><h2>由 JA 直接发布活动或成长内容</h2><p>JA 发布内容无需再次审核，会直接进入学生端。活动可设置报名字段，报名结果会回到后台“报名数据”。</p></div><div className="publish-kind"><button className={kind==="activity"?"active":""} onClick={()=>setKind("activity")}>成长活动</button><button className={kind==="content"?"active":""} onClick={()=>setKind("content")}>文章 / 视频</button></div><div className="admin-publisher-fields"><label>标题<input value={form.title} onChange={e=>change("title",e.target.value)} placeholder={kind==="activity"?"活动名称":"内容标题"}/></label><label>内容分类<input value={form.category} onChange={e=>change("category",e.target.value)}/></label><label className="full">简介<textarea rows={4} value={form.summary} onChange={e=>change("summary",e.target.value)} placeholder="请清晰说明活动或内容的价值"/></label>{kind==="activity"?<><label>活动地点<input value={form.place} onChange={e=>change("place",e.target.value)}/></label><label>活动日期<input type="date" value={form.date} onChange={e=>change("date",e.target.value)}/></label><label>人数上限<input type="number" min="1" value={form.capacity} onChange={e=>change("capacity",e.target.value)}/></label><fieldset className="registration-config full"><legend>报名表需要学生填写</legend><div>{fieldOptions.map(field=><label key={field.id}><input type="checkbox" checked={fields.includes(field.id)} onChange={()=>setFields(v=>v.includes(field.id)?v.filter(x=>x!==field.id):[...v,field.id])}/><span>{field.label}</span><small>{field.required?"必填":"选填"}</small></label>)}</div><label>自定义问题（每行一个）<textarea rows={3} value={custom} onChange={e=>setCustom(e.target.value)}/></label></fieldset></>:<><label>阅读 / 观看时长<input value={form.duration} onChange={e=>change("duration",e.target.value)}/></label><label>内容形式<select value={form.mediaType} onChange={e=>change("mediaType",e.target.value)}><option value="article">图文文章</option><option value="video">视频</option></select></label></>}<label className="media-upload full">封面图片或视频<input type="file" accept="image/*,video/mp4,video/webm" onChange={e=>media(e.target.files?.[0])}/><span>{form.cover?"✓ 已设置封面":"选择文件"}</span></label></div><button className="admin-publish-button" disabled={saving} onClick={publish}>{saving?"正在发布…":"立即发布到学生端 →"}</button></section>
}

function RegistrationTable({items,onSelect,onRefresh}:{items:Registration[];onSelect:(item:Registration)=>void;onRefresh:()=>void}){return <><div className="admin-data-head"><div><b>{items.length}</b><span>条活动报名</span></div><p>JA 可查看全部活动报名；企业只会看到自己发布活动的数据。</p><button onClick={onRefresh}>刷新数据</button></div>{items.length===0?<div className="admin-empty">还没有学生提交报名信息</div>:<div className="registration-table"><div className="registration-row head"><b>活动</b><b>姓名</b><b>联系电话</b><b>学校</b><b>详情</b></div>{items.map(item=><div className="registration-row" key={item.id}><strong>{item.activityTitle}</strong><span>{item.answers.name||"未填写"}</span><span>{item.answers.phone||"未填写"}</span><span>{item.answers.school||"未填写"}</span><button onClick={()=>onSelect(item)}>查看完整报名表</button></div>)}</div>}</>}

function RegistrationDrawer({item,onClose}:{item:Registration;onClose:()=>void}){return <div className="admin-review-drawer registration-drawer"><button className="drawer-close" onClick={onClose}>×</button><small>活动报名详情</small><h1>{item.activityTitle}</h1><div className="registration-answer-list">{Object.entries(item.answers).map(([key,value])=><p key={key}><b>{({name:"姓名",phone:"联系电话",email:"邮箱",school:"学校与专业",studentId:"学号",expectation:"活动期待"} as Record<string,string>)[key]||key}</b><span>{value||"未填写"}</span></p>)}</div><p className="review-result">提交时间：{new Date(item.createdAt).toLocaleString("zh-CN")}</p></div>}

function ReviewDrawer({selected,reason,setReason,decide,close}:{selected:RecordItem;reason:string;setReason:(value:string)=>void;decide:(decision:"approved"|"rejected")=>void;close:()=>void}){return <div className="admin-review-drawer"><button className="drawer-close" onClick={close}>×</button><small>{kindName(selected.kind)}审核详情</small><h1>{String(selected.payload.title||"未命名")}</h1><div className="review-meta"><span><b>企业</b>{String(selected.payload.company||"长沙企业")}</span>{selected.kind==="job"&&<><span><b>岗位类别</b>{String(selected.payload.jobCategory||"未选择")}</span><span><b>工作城市</b>{String(selected.payload.city||"长沙")}</span><span><b>招聘邮箱</b>{String(selected.payload.contactEmail||"未填写")}</span></>}</div>{selected.payload.cover&&<img src={String(selected.payload.cover)} alt="发布方上传的审核素材"/>}<h3>简介</h3><p>{String(selected.payload.summary||"无")}</p>{Array.isArray(selected.payload.registrationFields)&&<><h3>活动报名字段</h3><ul>{(selected.payload.registrationFields as Field[]).map(field=><li key={field.id}>{field.label} · {field.required?"必填":"选填"}</li>)}</ul></>}{Array.isArray(selected.payload.responsibilities)&&<><h3>岗位职责</h3><ul>{selected.payload.responsibilities.map(x=><li key={String(x)}>{String(x)}</li>)}</ul></>}{Array.isArray(selected.payload.requirements)&&<><h3>能力要求</h3><ul>{selected.payload.requirements.map(x=><li key={String(x)}>{String(x)}</li>)}</ul></>}<label>JA 审核意见<textarea rows={4} value={reason} onChange={e=>setReason(e.target.value)} placeholder="通过时可填写确认意见；退回时必须说明修改内容"/></label>{(!selected.payload.reviewStatus||selected.payload.reviewStatus==="pending")?<div className="drawer-actions"><button onClick={()=>decide("rejected")}>退回企业修改</button><button className="approve" onClick={()=>decide("approved")}>审核通过并公开</button></div>:<p className="review-result">当前状态：{stateName(selected.payload.reviewStatus)}<br/>{String(selected.payload.reviewNote||"")}</p>}</div>}
