import {env} from "cloudflare:workers";
import {getChatGPTUser} from "../../chatgpt-auth";

async function setup(){await env.DB.batch([env.DB.prepare("CREATE TABLE IF NOT EXISTS workspace_records (id TEXT PRIMARY KEY, owner_id TEXT NOT NULL, kind TEXT NOT NULL, payload TEXT NOT NULL, updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)"),env.DB.prepare("CREATE TABLE IF NOT EXISTS audit_logs (id INTEGER PRIMARY KEY AUTOINCREMENT, actor_id TEXT NOT NULL, action TEXT NOT NULL, target_type TEXT NOT NULL, target_id TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)"),env.DB.prepare("CREATE TABLE IF NOT EXISTS activity_registrations (id TEXT PRIMARY KEY, activity_id TEXT NOT NULL, activity_title TEXT NOT NULL, student_owner_id TEXT NOT NULL, publisher_owner_id TEXT NOT NULL, answers TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'registered', created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)"),env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_activity_registration_publisher ON activity_registrations(publisher_owner_id, created_at)")])}
function allowed(email:string){const value=(env as unknown as {JA_ADMIN_EMAILS?:string}).JA_ADMIN_EMAILS??"";return value.split(",").map(x=>x.trim().toLowerCase()).filter(Boolean).includes(email.toLowerCase())}
async function admin(request:Request){const user=await getChatGPTUser();if(user&&allowed(user.email))return {id:user.userId,email:user.email};const url=new URL(request.url);const local=url.hostname==="localhost"||url.hostname==="127.0.0.1";const supplied=request.headers.get("x-ja-admin-test")||url.searchParams.get("admin_test_key");if(local&&supplied==="local-ja-audit-test")return {id:"local-ja-test",email:"local-test@ja.invalid"};return {id:null,email:user?.email??null}}
export async function GET(request:Request){await setup();const user=await admin(request);if(!user.id)return Response.json({error:"需要后台登录"},{status:401});const [records,logs,registrations]=await env.DB.batch([env.DB.prepare("SELECT id,owner_id AS ownerId,kind,payload,updated_at AS updatedAt FROM workspace_records ORDER BY updated_at DESC LIMIT 200"),env.DB.prepare("SELECT id,actor_id AS actorId,action,target_type AS targetType,target_id AS targetId,created_at AS createdAt FROM audit_logs ORDER BY created_at DESC LIMIT 200"),env.DB.prepare("SELECT id,activity_id AS activityId,activity_title AS activityTitle,answers,status,created_at AS createdAt FROM activity_registrations ORDER BY created_at DESC LIMIT 500")]);return Response.json({operator:user.email,records:records.results.map(r=>({...r,payload:JSON.parse(String(r.payload))})),logs:logs.results,registrations:registrations.results.map(r=>({...r,answers:JSON.parse(String(r.answers))}))})}
export async function POST(request:Request){await setup();const user=await admin(request);if(!user.id)return Response.json({error:"需要后台登录或管理员权限"},{status:401});const body=await request.json() as {id?:string;decision?:"approved"|"rejected";reason?:string};if(!body.id||!body.decision)return Response.json({error:"缺少审核信息"},{status:400});if(body.decision==="rejected"&&!body.reason?.trim())return Response.json({error:"退回时必须填写修改意见"},{status:400});const row=await env.DB.prepare("SELECT kind,payload FROM workspace_records WHERE id=?").bind(body.id).first();if(!row)return Response.json({error:"内容不存在"},{status:404});const current=JSON.parse(String(row.payload));const payload={...current,reviewStatus:body.decision,reviewNote:body.reason?.trim()||(body.decision==="approved"?"信息完整，JA 审核通过":""),reviewedAt:new Date().toISOString(),reviewedBy:user.email,status:body.decision==="approved"?(String(row.kind)==="job"?"招募中":"已发布"):"已退回"};await env.DB.prepare("UPDATE workspace_records SET payload=?,updated_at=CURRENT_TIMESTAMP WHERE id=?").bind(JSON.stringify(payload),body.id).run();await env.DB.prepare("INSERT INTO audit_logs(actor_id,action,target_type,target_id) VALUES(?,?,'review',?)").bind(user.id,body.decision,body.id).run();return Response.json({ok:true,reviewStatus:body.decision})}

export async function PUT(request:Request){
 await setup();const user=await admin(request);if(!user.id)return Response.json({error:"需要后台登录或管理员权限"},{status:401});
 const body=await request.json() as {kind?:"activity"|"content";payload?:Record<string,unknown>};
 if(!body.kind||!["activity","content"].includes(body.kind)||!body.payload)return Response.json({error:"发布类型不正确"},{status:400});
 if(!String(body.payload.title||"").trim()||!String(body.payload.summary||"").trim())return Response.json({error:"请填写标题与简介"},{status:400});
 const id=crypto.randomUUID();const now=new Date().toISOString();
 const payload={...body.payload,id,place:body.kind==="activity"?String(body.payload.place||"长沙"):body.payload.place,reviewStatus:"approved",reviewNote:"JA 后台直接发布",reviewedAt:now,reviewedBy:user.email,submittedAt:now,status:"已发布"};
 const json=JSON.stringify(payload);if(json.length>24000)return Response.json({error:"内容过长"},{status:400});
 await env.DB.prepare("INSERT INTO workspace_records(id,owner_id,kind,payload,updated_at) VALUES(?,?,?,?,CURRENT_TIMESTAMP)").bind(id,`ja:${user.id}`,body.kind,json).run();
 await env.DB.prepare("INSERT INTO audit_logs(actor_id,action,target_type,target_id) VALUES(?,'direct-publish',?,?)").bind(user.id,body.kind,id).run();
 return Response.json({ok:true,id});
}
